### ISSUE TITLE
Prevent Key Capture if tab isn't open

### ISSUE THREAD

**Issue by ryanproud** [tsmango/overcast-media-keys#2]
Is it possible to prevent capturing the media keys if an overcast tab isn't open.  The plugin works great, but it seems like I lose the ability to control iTunes even if not listening to overcast.

**Comment by tsmango** [comment]
Hey @ryanproud. Unfortunately, I haven't found a way around this behavior in Chrome, while still keeping the shortcuts global. The only thing I can suggest is going to the Settings > Extensions area, scrolling to the bottom, clicking "Keyboard Shortcuts", and changing each from "Global" to "In Chrome". Chrome will need to be the frontmost app for keyboard shortcuts to be picked up, though.

**Comment by ryanproud** [comment]
When I set it to "In Chrome" it doesn't capture the buttons at all.  Maybe it's a mac issue.
