### ISSUE TITLE
Sort by Date Descending

### ISSUE THREAD

**Issue by geneh74** [tsmango/overcast-media-keys#3]
Thanks for your great extension. I see the Sort by Date feature sorts by date _ascending from oldest to newest_ podcasts. Please consider adding a sort by date _descending from newest to oldest_ also. Thanks again!

**Comment by tsmango** [comment]
Hey @geneh74, great idea! I've just published an update (v1.3) with a few design tweaks, as well as this additional option. If the Chrome Web Store is still showing v1.2 for you, just give it a bit more time and it'll be updated for you.

![screenshot](https://cloud.githubusercontent.com/assets/9503/16243204/163f1d36-37c4-11e6-8551-01ce05e1df6e.png)

Thanks again!
